### ISSUE TITLE
"Cancel" button doesn't work

### ISSUE THREAD

**Issue by itsragedev** [SUFandom/proot-distro-tui#2]
Every time I press the cancel button it says "Aborting...", then nothing happens for a few seconds and finally it returns to the TUI menu again. One time I also saw an error message from "main.sh" for a few milliseconds.

**Comment by SUFandom** [comment]
Yeah it's an issue because of `while true ; do` mechanism, actually if you try to move to the other options, the script (main.sh) is running at background (see `ps -a` for info) that's why it's on loop, I'm currently trying to brainstorm this. But to get out, spam ESC a lot until you can get out. That's just temporary fix for now.

**Comment by itsragedev** [comment]
> Yeah it's an issue because of `while true ; do` mechanism

I've looked into the source and can confirm is. My guess is that the program is trying to exit with `exit 255`, but at the same time attempts to launch another instance of itself because it instantly goes back to the beginning of the while loop. So yeah, something should be done here. But thanks anyways for reaching out. I'll see if I can attempt to fix this.

**Comment by SUFandom** [comment]
I fixed it

_by getting rid of it.. but this thread will stay up just in case for a month_

**Comment by SUFandom** [comment]
This issue is now closed early, no one is having issues with this
